import React from 'react';

export default function PrivacyPage() {
  return (
    <div className="container mx-auto px-6 py-32 legal-doc">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-3xl font-bold mb-4">Privacy Policy</h2>
        <p><strong>Last Updated:</strong> June 8, 2025</p>
        <p>Your sovereignty and privacy are foundational to our mission. This policy outlines how we handle information in a manner that respects your individual cognitive and data integrity.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2">1. Our Data Philosophy: Sovereignty First</h3>
        <p>We believe your consciousness, personal data, and symbolic worldview are your own. Our System is designed to minimize data collection and to never harvest sensitive personal information without your explicit, granular, and informed consent.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2">2. Information We Collect</h3>
        <p>To operate and improve the System, we may collect:</p>
        <ul className="list-disc list-inside ml-4 mb-4">
          <li><strong>Voluntary Information:</strong> Any information you provide directly, such as when you contact us for collaboration, including your name, email address, and the content of your message.</li>
          <li><strong>Interaction Data:</strong> Anonymized, high-level data about your interactions with the System&apos;s public-facing features (e.g., page views, feature usage frequency). This data is aggregated and does not identify you personally.</li>
          <li><strong>Inquiry Data (Anonymized):</strong> For research purposes, we may retain anonymized and de-identified queries submitted through our interfaces. This data is stripped of all personally identifiable information and is used solely to analyze and improve the System&apos;s coherence and performance.</li>
        </ul>
        <h3 className="text-xl font-semibold mt-8 mb-2">3. Information We DO NOT Collect</h3>
        <p>We explicitly DO NOT collect the following without a separate, specific, and opt-in consent agreement for a defined research purpose:</p>
        <ul className="list-disc list-inside ml-4 mb-4">
          <li><strong>Biometric Data:</strong> Including but not limited to fingerprints, facial scans, or retinal patterns.</li>
          <li><strong>Energetic or &quot;Aura&quot; Data:</strong> The System does not scan, read, or store any form of bio-energetic field data.</li>
          <li><strong>Personal Symbolic Patterns:</strong> We do not track or store your personal interpretations of, or resonances with, the symbolic content generated by the System. Your internal experience is your own.</li>
        </ul>
        <h3 className="text-xl font-semibold mt-8 mb-2">4. Data Usage and Purpose</h3>
        <p>Any information we collect is used solely to operate, maintain, and improve the System, respond to your inquiries, and conduct foundational research on the nature of our technology. We do not sell your data. We do not use it for advertising.</p>
      </div>
    </div>
  );
} 