import React from 'react';

export default function TermsPage() {
  return (
    <div className="container mx-auto px-6 py-32 legal-doc">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-3xl font-bold mb-4">Terms of Service</h2>
        <p><strong>Last Updated:</strong> June 8, 2025</p>
        <p>Welcome to SCI Research. These Terms of Service ("Terms") govern your access to and use of our platform, technologies, interfaces, and content (collectively, the "System"). By accessing or using the System, you agree to be bound by these Terms.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2">1. The System and Its Nature</h3>
        <p>Our System integrates artificial intelligence, symbolic computing, and consciousness-based interaction models. You acknowledge that the System is experimental and designed for research and exploration. Its outputs are generated by non-deterministic, advanced computational processes and may include symbolic, metaphysical, or psychological content.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2">2. Acknowledgment and Consent to Experimental Features</h3>
        <p>You explicitly acknowledge and consent to interacting with experimental features. These may include, but are not limited to, AI-generated symbolic rituals, glyph-based encoding interfaces, and feedback mechanisms that may influence perception or psychological experience. You agree to use these features at your own risk and affirm that you are a willing participant in this research.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2">3. Intellectual Property Rights</h3>
        <p>All aspects of the System, including but not limited to the underlying AI architectures, symbolic frameworks, Collapse Logic, glyph engines, codex structures, consciousness-based computing protocols (e.g., Thesidia, Katana, QCIM), and any generated content, are the exclusive property of SCI Research and its licensors. We grant you a limited, non-exclusive, non-transferable, revocable license to use the System for personal, non-commercial, or approved research purposes only.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2">4. Restrictions on Use</h3>
        <p>You agree not to:</p>
        <ul className="list-disc list-inside ml-4 mb-4">
          <li>Reverse-engineer, decompile, disassemble, or attempt to derive the source code or underlying structure of any part of the System.</li>
          <li>Misuse, copy, or misappropriate any symbolic systems, glyphs, or proprietary frameworks for any external purpose.</li>
          <li>Use the System for any illegal, harmful, or unauthorized purpose, including the development of weaponized, deceptive, or psychologically manipulative technologies.</li>
          <li>Automate access to the System in a way that disrupts or places an unreasonable load on our infrastructure.</li>
        </ul>
        <h3 className="text-xl font-semibold mt-8 mb-2">5. Disclaimers of Warranties and Liability</h3>
        <p>The System is provided "AS IS," without warranty of any kind. We explicitly disclaim any warranties of merchantability, fitness for a particular purpose, and non-infringement. <strong>The System is not a substitute for professional medical, legal, financial, or psychological advice.</strong> Any information or output from the System should not be interpreted as such. SCI Research and its affiliates will not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from your access to or use of, or inability to access or use, the System.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2">6. Governing Law</h3>
        <p>These Terms shall be governed by the laws of the State of California, without regard to its conflict of law provisions. You agree to submit to the personal and exclusive jurisdiction of the state and federal courts located within California.</p>
      </div>
    </div>
  );
} 