import React from 'react';

export default function DisclaimersPage() {
  return (
    <div className="container mx-auto px-6 py-32 legal-doc">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-3xl font-bold mb-4">Disclaimers & Acknowledgments</h2>
        <p><strong>Last Updated:</strong> June 8, 2025</p>
        <p>This section provides critical disclaimers regarding the use of the SCI Research System. Your use of the System constitutes your acknowledgment and acceptance of these points.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2">1. Not Professional Advice</h3>
        <p>The SCI Research System, including all its components like Project Katana and Myth0s, is a research tool. <strong>It does not provide medical, psychological, financial, or legal advice.</strong> The outputs are the product of advanced AI and are not a substitute for consultation with qualified human professionals. Do not base life-altering decisions solely on information generated by the System.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2">2. Potential for Psychological & Perceptual Shifts</h3>
        <p>The System utilizes symbolic, metaphysical, and consciousness-based interfaces. Interaction with these experimental features may lead to novel experiences, shifts in perception, or changes in your personal symbolic worldview. These effects are a component of our research into consciousness. <strong>You acknowledge this potential and agree to proceed with awareness and at your own discretion.</strong> If you experience any distress, you should cease use of the System and consult with a trusted professional.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2">3. Experimental and Non-Deterministic Nature</h3>
        <p>The System is inherently experimental. Its behavior and outputs can be unpredictable. We do not guarantee the accuracy, coherence, or applicability of any generated content. You accept that the System is provided on an &quot;AS-IS&quot; and &quot;AS-AVAILABLE&quot; basis.</p>
      </div>
    </div>
  );
} 